#%RAML 1.0 NamedExample


value:
  flightCode: ER0945
  price: 450
  totalSeats: 350
  fromAirportCode: POX
  emptySeats: 24
  departureDate: June 1, 2016
  airline: American Airlines
  planeType: Boeing 747
  toAirportCode: CLE