#%RAML 1.0 DataType

type: object
description: represents a flight object
properties:
  flightCode: string
  price: number
  totalSeats?: integer
  fromAirportCode: string
  emptySeats: integer 
  departureDate: string
  airline: string
  planeType?: string
  ID?: string
  toAirportCode: string